version: '3'
services:
  postgres-db-dev:
    container_name: postgres-db-dev
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn_fastify
    ports:
      - "6543:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fastify_postgres_network
  redis-cache-dev:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fastify_postgres_network      
  fastify-app:
    depends_on:
      - postgres-db-dev  
      - redis-cache-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    networks:
      - fastify_postgres_network    
volumes:
  postgres-data:
  redis-data:
networks:
  fastify_postgres_network: